# Generated by Django 3.2.4 on 2021-06-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
    ]
